# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(352, 258)
        self.gridLayoutWidget = QtWidgets.QWidget(SettingsWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.md5_info_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.md5_info_lb.setFont(font)
        self.md5_info_lb.setObjectName("md5_info_lb")
        self.gridLayout.addWidget(self.md5_info_lb, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.text_info_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.text_info_lb.setFont(font)
        self.text_info_lb.setObjectName("text_info_lb")
        self.gridLayout.addWidget(self.text_info_lb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 3, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(SettingsWidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 210, 131, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid #000000;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(230, 230, 230)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid #000000;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Form"))
        self.md5_info_lb.setText(_translate("SettingsWidget", "MD555555555"))
        self.label_4.setText(_translate("SettingsWidget", "编辑文本："))
        self.label.setText(_translate("SettingsWidget", "原始文本信息："))
        self.text_info_lb.setText(_translate("SettingsWidget", "文字"))
        self.label_2.setText(_translate("SettingsWidget", "文本MD5："))
        self.textEdit.setHtml(_translate("SettingsWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文字</p></body></html>"))
        self.pushButton.setText(_translate("SettingsWidget", "生成音频"))
